"""i3 Timestamp helpers.

Covers: NENA-STA-010.3f-2021 §2.3.

Key requirements from the standard:
  • RFC 3339 / ISO 8601 date-time format.
  • LOCAL time — not UTC/"Z" — with a mandatory UTC offset.
  • Offset MUST be based on the creator's local time.
  • Sub-second precision (decimal seconds) MUST be included when two or more
    Timestamps could be generated by the same element within one second.
  • Trailing zeros in the fractional-seconds field may be omitted (example in
    the standard: "2015-08-21T12:58:03.01-05:00").
"""

from __future__ import annotations

from datetime import datetime, timezone


def now_i3() -> datetime:
    """Return the current moment as a timezone-aware datetime in local time.

    Callers who need the formatted string immediately can pass the result
    straight to format_i3().
    """
    # datetime.now(tz=utc).astimezone() converts to the platform local timezone,
    # preserving the UTC offset so format_i3() can render it correctly.
    return datetime.now(tz=timezone.utc).astimezone()


def format_i3(dt: datetime) -> str:
    """Format *dt* as an i3 Timestamp string per §2.3.

    The returned string is always of the form::

        YYYY-MM-DDTHH:MM:SS[.f+]-HH:MM   (local time, explicit UTC offset)

    A bare "Z" suffix is never emitted — the standard requires the offset to
    reflect the creator's local time zone even when that offset is +00:00.

    Args:
        dt: A timezone-aware datetime.  Naïve datetimes are rejected.

    Returns:
        RFC 3339 string in local time with an explicit numeric UTC offset.

    Raises:
        ValueError: If *dt* is naïve (no tzinfo).
    """
    if dt.tzinfo is None:
        raise ValueError(
            "format_i3 requires a timezone-aware datetime; "
            "use now_i3() or attach tzinfo before calling."
        )

    # Convert to the platform local timezone — this is the "creator's local time"
    # required by §2.3.  If dt is already in local time the conversion is a no-op.
    local_dt = dt.astimezone()

    # Build the date/time part.
    base = local_dt.strftime("%Y-%m-%dT%H:%M:%S")

    # Fractional seconds: strip trailing zeros so "010000 µs" → ".01" not ".010000".
    if local_dt.microsecond:
        frac = f"{local_dt.microsecond:06d}".rstrip("0")
        base = f"{base}.{frac}"

    # Explicit numeric offset — never "Z".
    offset = local_dt.utcoffset()
    assert offset is not None  # guaranteed after astimezone()
    total_secs = int(offset.total_seconds())
    sign = "+" if total_secs >= 0 else "-"
    total_secs = abs(total_secs)
    hh, remainder = divmod(total_secs, 3600)
    mm = remainder // 60
    return f"{base}{sign}{hh:02d}:{mm:02d}"


def parse_i3(s: str) -> datetime:
    """Parse an i3 Timestamp string into a timezone-aware datetime.

    Accepts any RFC 3339 date-time, including +00:00 and Z suffixes.
    """
    # fromisoformat handles "+HH:MM" and "Z" from Python 3.11+.
    return datetime.fromisoformat(s)
