"""ElementState event package.

Covers: NENA-STA-010.3f-2021 §2.4.1 (Element State) + §10.13 (elementState registry).

Subscriber note (§2.4.1):
    If a subscriber is unable to contact an element it MUST locally assume the
    element's state is "Unreachable".  That inference is the subscriber's
    responsibility and is NOT generated by this notifier.

Transport constants (consumed by the SIP NOTIFY transport, Prompt 4):
    NOTIFY_MIME_TYPE    — MIME type for the NOTIFY body.
    EVENT_PACKAGE_NAME  — SIP Event header value for SUBSCRIBE/NOTIFY.
"""

from __future__ import annotations

import asyncio
import logging
import time
from collections.abc import Callable
from typing import Any

from i3_fe_core.config.identity import ElementIdentity
from i3_fe_core.state.store import ElementState, ElementStateBundle, StateStore

_log = logging.getLogger(__name__)

# IANA SIP Event Package: emergency-ElementState (§2.4.1)
EVENT_PACKAGE_NAME: str = "emergency-ElementState"

# MIME type for the NOTIFY body (§2.4.1)
NOTIFY_MIME_TYPE: str = "Application/EmergencyCallData.ElementState+json"

# Canonical set of §10.13 registry values — used in conformance assertions.
ELEMENT_STATE_REGISTRY: frozenset[str] = frozenset(e.value for e in ElementState)

# Re-export so callers only need to import from this module.
__all__ = [
    "ElementState",
    "ElementStateNotifier",
    "ELEMENT_STATE_REGISTRY",
    "EVENT_PACKAGE_NAME",
    "NOTIFY_MIME_TYPE",
]


class ElementStateNotifier:
    """Maintains and publishes ElementState per §2.4.1.

    Usage::

        notifier = ElementStateNotifier(identity, store, min_notify_interval=1.0)
        notifier.subscribe(my_sip_transport.send_notify)
        notifier.set_state(ElementState.SERVICE_DISRUPTION, "DB pool exhausted")

    Rate filtering (RFC 6446 / §2.4.1):
        When *min_notify_interval* > 0, changes arriving faster than the
        interval are coalesced: the latest state wins and a single NOTIFY is
        dispatched when the timer fires.  If no asyncio event loop is running
        (synchronous / test context) the notification is sent immediately as a
        safe fallback.
    """

    def __init__(
        self,
        identity: ElementIdentity,
        store: StateStore,
        min_notify_interval: float = 0.0,
    ) -> None:
        """
        Args:
            identity:             FE identity; element_id populates the NOTIFY body.
            store:                StateStore holding the authoritative current state.
            min_notify_interval:  RFC 6446 minimum seconds between NOTIFYs (0 = off).
        """
        self._identity = identity
        self._store = store
        self._min_interval = min_notify_interval
        self._callbacks: list[Callable[[dict[str, Any]], None]] = []
        # Monotonic reference for last dispatch; 0.0 ensures first notify is always immediate.
        self._last_notify_mono: float = 0.0
        self._notify_pending: bool = False

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def subscribe(self, callback: Callable[[dict[str, Any]], None]) -> None:
        """Register a callback invoked with the NOTIFY body dict on each dispatch."""
        self._callbacks.append(callback)

    def set_state(self, state: ElementState, reason: str = "") -> None:
        """Transition to *state*.

        No-op if state and reason are unchanged.  Logs every genuine transition.
        Schedules a NOTIFY dispatch subject to the RFC 6446 rate filter.
        """
        current = self._store.get_element_state()
        if current.state == state and current.reason == reason:
            return

        _log.info(
            "ElementState %s → %s (reason=%r)",
            current.state,
            state.value,
            reason,
        )
        self._store.set_element_state(ElementStateBundle(state=state, reason=reason))
        self._schedule_notify()

    def get_notify_body(self) -> dict[str, Any]:
        """Return the §2.4.1 NOTIFY body dict for the current state.

        Fields:
            elementId  MANDATORY — from injected ElementIdentity.element_id
            state      MANDATORY — §10.13 registry string value
            reason     OPTIONAL  — omitted when empty
        """
        bundle = self._store.get_element_state()
        body: dict[str, Any] = {
            "elementId": self._identity.element_id,
            "state": bundle.state.value,
        }
        if bundle.reason:
            body["reason"] = bundle.reason
        return body

    # ------------------------------------------------------------------
    # Internal: rate filter (RFC 6446)
    # ------------------------------------------------------------------

    def _schedule_notify(self) -> None:
        elapsed = time.monotonic() - self._last_notify_mono
        remaining = self._min_interval - elapsed

        if remaining <= 0:
            # Rate window has passed (or no minimum set) — dispatch immediately.
            self._dispatch_notify()
            return

        # We are inside the rate-limit window.
        if self._notify_pending:
            # A deferred dispatch is already queued; it will pick up the latest
            # state from the store when it fires — no second timer needed.
            return

        # Attempt to defer via the running asyncio loop.
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            # No event loop (synchronous / test context) — fall back to
            # immediate dispatch rather than silently dropping the notification.
            self._dispatch_notify()
            return

        self._notify_pending = True
        loop.call_later(remaining, self._deferred_dispatch)

    def _deferred_dispatch(self) -> None:
        self._notify_pending = False
        self._dispatch_notify()

    def _dispatch_notify(self) -> None:
        self._last_notify_mono = time.monotonic()
        body = self.get_notify_body()
        for cb in self._callbacks:
            try:
                cb(body)
            except Exception:
                _log.exception("ElementState subscriber callback raised")
