"""ServiceState event package.

Covers: NENA-STA-010.3f-2021 §2.4.2 (Service State) + §10.12 (serviceState
registry) + §10.18 (securityPosture registry).

Subscriber note (§2.4.2):
    If a subscriber is unable to contact a service it MUST locally assume the
    service's state is "Unreachable".  That inference is the subscriber's
    responsibility and is NOT generated by this notifier.

Aggregate seam (§2.4.2, §4.3.2.7, §4.4, §4.5):
    ServiceState is a SERVICE-level concept that may span a set of redundant
    FE nodes.  The standard recommends a single state-level service rather than
    per-node publishing.  Accordingly, ServiceStateNotifier is driven by
    set_state() / set_security_posture() calls from EXTERNAL LOGIC — either
    this process's own condition-monitoring code, or a separate aggregator that
    combines element states from multiple nodes.  The notifier never derives
    service state from its own process's element state.

Transport constants (consumed by the SIP NOTIFY transport):
    NOTIFY_MIME_TYPE    — MIME type for the NOTIFY body.
    EVENT_PACKAGE_NAME  — SIP Event header value for SUBSCRIBE/NOTIFY.
"""

from __future__ import annotations

import asyncio
import logging
import time
from collections.abc import Callable
from typing import Any

from i3_fe_core.state.store import (
    SecurityPosture,
    SecurityPostureBundle,
    ServiceState,
    ServiceStateBundle,
    StateStore,
)

_log = logging.getLogger(__name__)

# IANA SIP Event Package: emergency-ServiceState (§2.4.2)
EVENT_PACKAGE_NAME: str = "emergency-ServiceState"

# MIME type for the NOTIFY body (§2.4.2)
NOTIFY_MIME_TYPE: str = "Application/EmergencyCallData.ServiceState+json"

# Canonical frozensets for conformance assertions.
SERVICE_STATE_REGISTRY: frozenset[str] = frozenset(e.value for e in ServiceState)
SECURITY_POSTURE_REGISTRY: frozenset[str] = frozenset(e.value for e in SecurityPosture)

# Re-export so callers only need to import from this module.
__all__ = [
    "ServiceState",
    "SecurityPosture",
    "ServiceStateNotifier",
    "SERVICE_STATE_REGISTRY",
    "SECURITY_POSTURE_REGISTRY",
    "EVENT_PACKAGE_NAME",
    "NOTIFY_MIME_TYPE",
]


class ServiceStateNotifier:
    """Maintains and publishes ServiceState per §2.4.2.

    Usage::

        notifier = ServiceStateNotifier(
            service="lvf.psap.allegheny.pa.us",
            name="LVF",                           # §10.11 token
            domain="lvf.psap.allegheny.pa.us",    # Service Identifier (MANDATORY)
            store=store,
            supports_security_posture=True,
        )
        notifier.subscribe(my_sip_transport.send_notify)
        notifier.set_state(ServiceState.OVERLOADED, "MSAG DB unreachable")
        notifier.set_security_posture(SecurityPosture.YELLOW, "SIP scan elevated")

    Aggregate seam:
        set_state() and set_security_posture() are the entry points for external
        aggregators.  A supervisor that watches multiple FE element states calls
        these to publish the combined service-level view without this notifier
        needing any knowledge of which FEs contribute.

    Rate filtering (RFC 6446 / §2.4.2):
        Same coalescing behaviour as ElementStateNotifier: rapid changes within
        *min_notify_interval* seconds are merged to one NOTIFY carrying the
        latest state.  Falls back to immediate dispatch when no asyncio loop
        is running.
    """

    def __init__(
        self,
        service: str,
        name: str,
        domain: str,
        store: StateStore,
        service_id: str | None = None,
        min_notify_interval: float = 0.0,
        supports_security_posture: bool = False,
        initial_security_posture: SecurityPosture = SecurityPosture.GREEN,
    ) -> None:
        """
        Args:
            service:                  URI/FQDN identifying the subscribed service.
            name:                     IANA serviceNames token (§10.11), e.g. "LVF".
            domain:                   Service Identifier FQDN — MANDATORY in body (§2.4.2).
            store:                    StateStore for authoritative state.
            service_id:               Optional; if provided MUST equal *domain* (§2.4.2 fn.4).
            min_notify_interval:      RFC 6446 minimum seconds between NOTIFYs (0 = off).
            supports_security_posture: When True the securityPosture object is
                                       always included in the NOTIFY body; when
                                       False it is never emitted.
            initial_security_posture: Starting SecurityPosture seeded into the store when
                                       supports_security_posture is True and the store has
                                       no posture yet.  Defaults to Green ("all clear").
                                       An FE opting into security-posture tracking SHOULD
                                       pass its real starting state so the first NOTIFY
                                       carries a deliberate value rather than a hidden default.
        """
        if service_id is not None and service_id != domain:
            raise ValueError(
                f"serviceId {service_id!r} MUST equal domain {domain!r} (§2.4.2)"
            )

        self._service = service
        self._name = name
        self._domain = domain
        self._service_id = service_id
        self._store = store
        self._min_interval = min_notify_interval
        self._supports_security_posture = supports_security_posture
        self._callbacks: list[Callable[[dict[str, Any]], None]] = []
        # Monotonic reference for last dispatch; 0.0 ensures first notify is immediate.
        self._last_notify_mono: float = 0.0
        self._notify_pending: bool = False

        # Seed the initial security posture so get_notify_body() always reads from
        # the store and the FE's starting state is explicit and log-visible.
        if supports_security_posture:
            current = store.get_service_state()
            if current.security_posture is None:
                store.set_service_state(
                    ServiceStateBundle(
                        state=current.state,
                        reason=current.reason,
                        security_posture=SecurityPostureBundle(
                            posture=initial_security_posture, reason=""
                        ),
                    )
                )
                _log.info(
                    "ServiceStateNotifier: seeded initial security posture → %s",
                    initial_security_posture.value,
                )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def subscribe(self, callback: Callable[[dict[str, Any]], None]) -> None:
        """Register a callback invoked with the NOTIFY body dict on each dispatch."""
        self._callbacks.append(callback)

    def set_state(self, state: ServiceState, reason: str = "") -> None:
        """Transition service state.

        No-op if state and reason are unchanged.  Intended to be called by
        this service's own monitoring logic or by an external aggregator.
        """
        current = self._store.get_service_state()
        if current.state == state and current.reason == reason:
            return

        _log.info(
            "ServiceState %s → %s (reason=%r)",
            current.state,
            state.value,
            reason,
        )
        self._store.set_service_state(
            ServiceStateBundle(
                state=state,
                reason=reason,
                security_posture=current.security_posture,
            )
        )
        self._schedule_notify()

    def set_security_posture(
        self,
        posture: SecurityPosture,
        reason: str = "",
    ) -> None:
        """Update the security posture (only relevant when supports_security_posture=True).

        No-op if posture and reason are unchanged.  Triggers a NOTIFY.
        """
        current = self._store.get_service_state()
        current_sp = current.security_posture
        if (
            current_sp is not None
            and current_sp.posture == posture
            and current_sp.reason == reason
        ):
            return

        _log.info(
            "SecurityPosture → %s (reason=%r)",
            posture.value,
            reason,
        )
        self._store.set_service_state(
            ServiceStateBundle(
                state=current.state,
                reason=current.reason,
                security_posture=SecurityPostureBundle(posture=posture, reason=reason),
            )
        )
        self._schedule_notify()

    def get_notify_body(self) -> dict[str, Any]:
        """Return the §2.4.2 NOTIFY body dict for the current state.

        Structure (§2.4.2 table):
            service       MANDATORY
            name          MANDATORY  — IANA serviceNames token (§10.11)
            serviceId     OPTIONAL   — if present MUST equal domain
            domain        MANDATORY  — Service Identifier FQDN
            serviceState  MANDATORY  — { state, reason }
                state     MANDATORY  — §10.12 registry string
                reason    MANDATORY  — empty string when no reason (§2.4.2)
            securityPosture CONDITIONAL — omitted entirely when unsupported
                posture   MANDATORY  — §10.18 registry string
                reason    OPTIONAL   — omitted when empty
        """
        bundle = self._store.get_service_state()

        body: dict[str, Any] = {
            "service": self._service,
            "name": self._name,
        }
        if self._service_id is not None:
            body["serviceId"] = self._service_id
        body["domain"] = self._domain

        body["serviceState"] = {
            "state": bundle.state.value,
            "reason": bundle.reason,  # MANDATORY — empty string if none
        }

        if self._supports_security_posture:
            sp = bundle.security_posture
            if sp is None:
                # Defensive guard — should not be reached after __init__ seeding.
                posture_body: dict[str, Any] = {"posture": SecurityPosture.GREEN.value}
            else:
                posture_body = {"posture": sp.posture.value}
                if sp.reason:
                    posture_body["reason"] = sp.reason
            body["securityPosture"] = posture_body

        return body

    # ------------------------------------------------------------------
    # Internal: rate filter (RFC 6446) — mirrors ElementStateNotifier
    # ------------------------------------------------------------------

    def _schedule_notify(self) -> None:
        elapsed = time.monotonic() - self._last_notify_mono
        remaining = self._min_interval - elapsed

        if remaining <= 0:
            self._dispatch_notify()
            return

        if self._notify_pending:
            return

        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            self._dispatch_notify()
            return

        self._notify_pending = True
        loop.call_later(remaining, self._deferred_dispatch)

    def _deferred_dispatch(self) -> None:
        self._notify_pending = False
        self._dispatch_notify()

    def _dispatch_notify(self) -> None:
        self._last_notify_mono = time.monotonic()
        body = self.get_notify_body()
        for cb in self._callbacks:
            try:
                cb(body)
            except Exception:
                _log.exception("ServiceState subscriber callback raised")
